name: Celix Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.3.0
      - name: Install conan and lcov
        run: |
          sudo apt-get install -yq --no-install-recommends lcov ninja-build
          sudo pip install conan==1.59.0
      - name: Setup Conan Profile
        run: |
          conan profile new default --detect
          conan profile update settings.build_type=Debug default
          #Note no backwards compatiblity for gcc5 needed, setting libcxx to c++11.
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Install Dependencies
        env:
          CONAN_BUILD_OPTIONS: |
            -o celix:enable_testing=True
            -o celix:build_all=True
            -o celix:enable_code_coverage=True
            -o celix:enable_testing_for_cxx14=True
            -o celix:enable_testing_dependency_manager_for_cxx11=True
            -o celix:enable_testing_on_ci=True
        run: |
          #force require libcurl 7.64.1, due to a sha256 verify issue in libcurl/7.87.0
          conan install . celix/ci -pr:b default -pr:h default -if build ${CONAN_BUILD_OPTIONS} -b missing -b cpputest --require-override=libcurl/7.64.1 --require-override=openssl/1.1.1s
      - name: Build
        run: |
          conan build . -bf build
      - name: Test with coverage
        run: |
          cd build
          source conanrun.sh
          make coverage
          source deactivate_conanrun.sh
          lcx="lcov --output-file=coverage.info " && for i in `find . -name "*.info.cleaned"`; do lcx+=" --add-tracefile=$i"; done && $lcx
      - name: Codecov
        uses: codecov/codecov-action@e156083f13aff6830c92fc5faa23505779fbf649
        with:
          file: build/coverage.info
          name: codecov-celix
